name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  PASSWORD: fake_password
  SECRET_KEY: fake_key
jobs:
  playwright:
    name: "Playwright"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build Application
        run: npx vite build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Setup Database
        run: npx wrangler d1 migrations apply MAIN_DB --local
      - name: "Create .dev.vars file"
        run: |
          touch .dev.vars
          echo PASSWORD=$PASSWORD >> .dev.vars
          echo SECRET_KEY=$SECRET_KEY >> .dev.vars
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
  vitest:
    name: "Vitest"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build Application
        run: npx vite build

      - name: Run Vitest
        run: npx vitest run --coverage
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: vitest-report
          path: coverage/
          retention-days: 7
